# .streamlit/secrets.toml
# DO NOT COMMIT THIS FILE TO PUBLIC REPOSITORIES!
SUPABASE_URL = "https://jtzsimjufmotufmwrzsc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0enNpbWp1Zm1vdHVmbXdyenNjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDA5MjI4NywiZXhwIjoyMDY1NjY4Mjg3fQ.OBeOGSKJGtY7GCCMx9-K29IuPivA6HgXPBKlC_HPNXY"